<a href="https://colab.research.google.com/github/ReynaraEzra/Classification-Tensorflow/blob/main/Classification_Iris.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
import tensorflow as tf
from google.colab import files

In [3]:
!pip install ipython-autotime
%load_ext autotime

time: 198 µs (started: 2021-06-29 01:39:56 +00:00)


In [61]:
uploaded = files.upload()

Saving Iris.csv to Iris (1).csv
time: 5.3 s (started: 2021-06-29 02:00:00 +00:00)


In [62]:
df = pd.read_csv('Iris.csv')

time: 5.8 ms (started: 2021-06-29 02:00:06 +00:00)


In [63]:
df

Id  SepalLengthCm  ...  PetalWidthCm         Species
0      1            5.1  ...           0.2     Iris-setosa
1      2            4.9  ...           0.2     Iris-setosa
2      3            4.7  ...           0.2     Iris-setosa
3      4            4.6  ...           0.2     Iris-setosa
4      5            5.0  ...           0.2     Iris-setosa
..   ...            ...  ...           ...             ...
145  146            6.7  ...           2.3  Iris-virginica
146  147            6.3  ...           1.9  Iris-virginica
147  148            6.5  ...           2.0  Iris-virginica
148  149            6.2  ...           2.3  Iris-virginica
149  150            5.9  ...           1.8  Iris-virginica

[150 rows x 6 columns]

time: 32.5 ms (started: 2021-06-29 02:00:06 +00:00)


In [64]:
df = df.drop('Id', axis=1)

time: 2.76 ms (started: 2021-06-29 02:00:06 +00:00)


In [65]:
category = pd.get_dummies(df['Species'])

time: 3.09 ms (started: 2021-06-29 02:00:06 +00:00)


In [66]:
category

Iris-setosa  Iris-versicolor  Iris-virginica
0              1                0               0
1              1                0               0
2              1                0               0
3              1                0               0
4              1                0               0
..           ...              ...             ...
145            0                0               1
146            0                0               1
147            0                0               1
148            0                0               1
149            0                0               1

[150 rows x 3 columns]

time: 20.9 ms (started: 2021-06-29 02:00:06 +00:00)


In [67]:
df_new = pd.concat([df, category], axis=1)

time: 2.28 ms (started: 2021-06-29 02:00:06 +00:00)


In [68]:
df_new

SepalLengthCm  SepalWidthCm  ...  Iris-versicolor  Iris-virginica
0              5.1           3.5  ...                0               0
1              4.9           3.0  ...                0               0
2              4.7           3.2  ...                0               0
3              4.6           3.1  ...                0               0
4              5.0           3.6  ...                0               0
..             ...           ...  ...              ...             ...
145            6.7           3.0  ...                0               1
146            6.3           2.5  ...                0               1
147            6.5           3.0  ...                0               1
148            6.2           3.4  ...                0               1
149            5.9           3.0  ...                0               1

[150 rows x 8 columns]

time: 40.9 ms (started: 2021-06-29 02:00:06 +00:00)


In [69]:
df_new = df_new.drop('Species', axis=1)

time: 2.8 ms (started: 2021-06-29 02:00:06 +00:00)


In [70]:
df_new

SepalLengthCm  SepalWidthCm  ...  Iris-versicolor  Iris-virginica
0              5.1           3.5  ...                0               0
1              4.9           3.0  ...                0               0
2              4.7           3.2  ...                0               0
3              4.6           3.1  ...                0               0
4              5.0           3.6  ...                0               0
..             ...           ...  ...              ...             ...
145            6.7           3.0  ...                0               1
146            6.3           2.5  ...                0               1
147            6.5           3.0  ...                0               1
148            6.2           3.4  ...                0               1
149            5.9           3.0  ...                0               1

[150 rows x 7 columns]

time: 34.6 ms (started: 2021-06-29 02:00:06 +00:00)


In [71]:
value = df_new.values

time: 1.47 ms (started: 2021-06-29 02:00:06 +00:00)


In [72]:
X = value[:,:4]
Y = value[:,4:7]

time: 1.68 ms (started: 2021-06-29 02:00:06 +00:00)


In [73]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

X_scaler = scaler.fit_transform(X)

time: 9.17 ms (started: 2021-06-29 02:00:06 +00:00)


In [74]:
X_scaler

array([[0.22222222, 0.625     , 0.06779661, 0.04166667],
       [0.16666667, 0.41666667, 0.06779661, 0.04166667],
       [0.11111111, 0.5       , 0.05084746, 0.04166667],
       [0.08333333, 0.45833333, 0.08474576, 0.04166667],
       [0.19444444, 0.66666667, 0.06779661, 0.04166667],
       [0.30555556, 0.79166667, 0.11864407, 0.125     ],
       [0.08333333, 0.58333333, 0.06779661, 0.08333333],
       [0.19444444, 0.58333333, 0.08474576, 0.04166667],
       [0.02777778, 0.375     , 0.06779661, 0.04166667],
       [0.16666667, 0.45833333, 0.08474576, 0.        ],
       [0.30555556, 0.70833333, 0.08474576, 0.04166667],
       [0.13888889, 0.58333333, 0.10169492, 0.04166667],
       [0.13888889, 0.41666667, 0.06779661, 0.        ],
       [0.        , 0.41666667, 0.01694915, 0.        ],
       [0.41666667, 0.83333333, 0.03389831, 0.04166667],
       [0.38888889, 1.        , 0.08474576, 0.125     ],
       [0.30555556, 0.79166667, 0.05084746, 0.125     ],
       [0.22222222, 0.625     ,

time: 15.9 ms (started: 2021-06-29 02:00:06 +00:00)


In [75]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X_scaler, Y, test_size=0.3, random_state=0)

time: 3.92 ms (started: 2021-06-29 02:00:06 +00:00)


In [76]:
model = tf.keras.models.Sequential([
                                    tf.keras.layers.Dense(units=64, activation='relu', input_shape=(4,)),
                                    tf.keras.layers.Dense(units=64, activation='relu'),
                                    tf.keras.layers.Dense(units=64, activation='relu'),
                                    tf.keras.layers.Dense(units=3, activation='softmax'),
])

time: 41 ms (started: 2021-06-29 02:00:06 +00:00)


In [77]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_6 (Dense)              (None, 64)                320       
_________________________________________________________________
dense_7 (Dense)              (None, 64)                4160      
_________________________________________________________________
dense_8 (Dense)              (None, 64)                4160      
_________________________________________________________________
dense_9 (Dense)              (None, 3)                 195       
Total params: 8,835
Trainable params: 8,835
Non-trainable params: 0
_________________________________________________________________
time: 12 ms (started: 2021-06-29 02:00:06 +00:00)


In [78]:
model.compile(
    optimizer='Adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

time: 9.59 ms (started: 2021-06-29 02:00:06 +00:00)


In [79]:
history = model.fit(
    X_train,
    Y_train,
    epochs=100
)

Epoch 1/100
4/4 [==============================] - 0s 4ms/step - loss: 1.0724 - accuracy: 0.3714
Epoch 2/100
4/4 [==============================] - 0s 3ms/step - loss: 1.0378 - accuracy: 0.3714
Epoch 3/100
4/4 [==============================] - 0s 3ms/step - loss: 1.0112 - accuracy: 0.4381
Epoch 4/100
4/4 [==============================] - 0s 3ms/step - loss: 0.9807 - accuracy: 0.5714
Epoch 5/100
4/4 [==============================] - 0s 4ms/step - loss: 0.9471 - accuracy: 0.6571
Epoch 6/100
4/4 [==============================] - 0s 4ms/step - loss: 0.9117 - accuracy: 0.6952
Epoch 7/100
4/4 [==============================] - 0s 4ms/step - loss: 0.8709 - accuracy: 0.6952
Epoch 8/100
4/4 [==============================] - 0s 4ms/step - loss: 0.8278 - accuracy: 0.6952
Epoch 9/100
4/4 [==============================] - 0s 4ms/step - loss: 0.7816 - accuracy: 0.6952
Epoch 10/100
4/4 [==============================] - 0s 3ms/step - loss: 0.7323 - accuracy: 0.6952
Epoch 11/100
4/4 [===========

In [80]:
model.evaluate(X_test, Y_test)

2/2 [==============================] - 0s 6ms/step - loss: 0.0665 - accuracy: 0.9778


[0.06646224856376648, 0.9777777791023254]

time: 190 ms (started: 2021-06-29 02:00:09 +00:00)


In [82]:
model.predict([[6.4, 2.7, 5.3, 1.9]])

array([[0.0000000e+00, 1.7277247e-17, 1.0000000e+00]], dtype=float32)

time: 66.6 ms (started: 2021-06-29 02:00:09 +00:00)


In [83]:
model.predict([[5.1, 2.5, 3, 1.1]])

array([[1.4029027e-29, 4.9067213e-09, 1.0000000e+00]], dtype=float32)

time: 66.5 ms (started: 2021-06-29 02:00:09 +00:00)
