<a href="https://colab.research.google.com/github/ReynaraEzra/Classification-Tensorflow/blob/main/Classification_Citrus_vs_Grapefruit_Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import pandas as pd
import numpy as np
import tensorflow as tf
from google.colab import files

time: 1.43 ms (started: 2021-06-28 17:52:43 +00:00)


In [4]:
!pip install ipython-autotime
%load_ext autotime

time: 166 µs (started: 2021-06-28 17:52:10 +00:00)


In [6]:
uploaded = files.upload()

Saving citrus.csv to citrus.csv
time: 21.2 s (started: 2021-06-28 17:52:52 +00:00)


In [40]:
df = pd.read_csv('citrus.csv')

time: 12.3 ms (started: 2021-06-28 17:59:14 +00:00)


In [41]:
df.head()

name  diameter  weight  red  green  blue
0  orange      2.96   86.76  172     85     2
1  orange      3.91   88.05  166     78     3
2  orange      4.42   95.17  156     81     2
3  orange      4.47   95.60  163     81     4
4  orange      4.48   95.76  161     72     9

time: 15.4 ms (started: 2021-06-28 17:59:15 +00:00)


In [42]:
df.tail()

name  diameter  weight  red  green  blue
9995  grapefruit     15.35  253.89  149     77    20
9996  grapefruit     15.41  254.67  148     68     7
9997  grapefruit     15.59  256.50  168     82    20
9998  grapefruit     15.92  260.14  142     72    11
9999  grapefruit     16.45  261.51  152     74     2

time: 18.5 ms (started: 2021-06-28 17:59:15 +00:00)


In [43]:
df.dtypes

name         object
diameter    float64
weight      float64
red           int64
green         int64
blue          int64
dtype: object

time: 6.13 ms (started: 2021-06-28 17:59:15 +00:00)


In [44]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   name      10000 non-null  object 
 1   diameter  10000 non-null  float64
 2   weight    10000 non-null  float64
 3   red       10000 non-null  int64  
 4   green     10000 non-null  int64  
 5   blue      10000 non-null  int64  
dtypes: float64(2), int64(3), object(1)
memory usage: 468.9+ KB
time: 13.9 ms (started: 2021-06-28 17:59:15 +00:00)


Mengubah string yang ada pada kolom 'name' menjadi bilangan numerik

In [45]:
df['name'][df['name'] == 'orange'] = 0 
df['name'][df['name'] == 'grapefruit'] = 1

time: 13.2 ms (started: 2021-06-28 17:59:15 +00:00)


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [46]:
df.head()

name  diameter  weight  red  green  blue
0    0      2.96   86.76  172     85     2
1    0      3.91   88.05  166     78     3
2    0      4.42   95.17  156     81     2
3    0      4.47   95.60  163     81     4
4    0      4.48   95.76  161     72     9

time: 14.3 ms (started: 2021-06-28 17:59:15 +00:00)


In [47]:
df.tail()

name  diameter  weight  red  green  blue
9995    1     15.35  253.89  149     77    20
9996    1     15.41  254.67  148     68     7
9997    1     15.59  256.50  168     82    20
9998    1     15.92  260.14  142     72    11
9999    1     16.45  261.51  152     74     2

time: 13.7 ms (started: 2021-06-28 17:59:15 +00:00)


In [49]:
value = df.values
value

array([[0, 2.96, 86.76, 172, 85, 2],
       [0, 3.91, 88.05, 166, 78, 3],
       [0, 4.42, 95.17, 156, 81, 2],
       ...,
       [1, 15.59, 256.5, 168, 82, 20],
       [1, 15.92, 260.14, 142, 72, 11],
       [1, 16.45, 261.51, 152, 74, 2]], dtype=object)

time: 7.51 ms (started: 2021-06-28 18:00:47 +00:00)


Kolom 1 atau kolom 'name' sebagai label dan kolom sisanya sebagai fitur

In [50]:
X = value[:, 1:6]
Y = value[:, 0]

time: 905 µs (started: 2021-06-28 18:01:55 +00:00)


In [51]:
X

array([[2.96, 86.76, 172, 85, 2],
       [3.91, 88.05, 166, 78, 3],
       [4.42, 95.17, 156, 81, 2],
       ...,
       [15.59, 256.5, 168, 82, 20],
       [15.92, 260.14, 142, 72, 11],
       [16.45, 261.51, 152, 74, 2]], dtype=object)

time: 2.68 ms (started: 2021-06-28 18:01:59 +00:00)


In [52]:
Y

array([0, 0, 0, ..., 1, 1, 1], dtype=object)

time: 7.05 ms (started: 2021-06-28 18:02:05 +00:00)


NN bekerja dengan baik pada rentang 0-1, oleh karena itu kita perlu mengubah nilai pada fitur menggunakan MinMaxScaler

In [53]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

X_scaler = scaler.fit_transform(X)
X_scaler

array([[0.        , 0.        , 0.74025974, 0.63529412, 0.        ],
       [0.07042254, 0.00738197, 0.66233766, 0.55294118, 0.01851852],
       [0.10822832, 0.04812589, 0.53246753, 0.58823529, 0.        ],
       ...,
       [0.93624907, 0.97133047, 0.68831169, 0.6       , 0.33333333],
       [0.96071164, 0.99216023, 0.35064935, 0.48235294, 0.16666667],
       [1.        , 1.        , 0.48051948, 0.50588235, 0.        ]])

time: 15.9 ms (started: 2021-06-28 18:03:40 +00:00)


Akan dipisahkan data sebagai data train dan data test

In [54]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X_scaler, Y, test_size = 0.3, random_state = 0)

time: 3.24 ms (started: 2021-06-28 18:05:40 +00:00)


In [55]:
Y_train = Y_train.astype('float32')
Y_test = Y_test.astype('float32')

time: 1.17 ms (started: 2021-06-28 18:06:18 +00:00)


In [ ]:
model = tf.keras.model.sequential([
                                   
])