<a href="https://colab.research.google.com/github/ReynaraEzra/Classification-Tensorflow/blob/main/Classification_Citrus_vs_Grapefruit_Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf
from google.colab import files

In [2]:
!pip install ipython-autotime
%load_ext autotime

time: 120 µs (started: 2021-06-28 18:34:47 +00:00)


In [3]:
uploaded = files.upload()

Saving citrus.csv to citrus (4).csv
time: 12.1 s (started: 2021-06-28 18:34:47 +00:00)


In [4]:
df = pd.read_csv('citrus.csv')

time: 14.2 ms (started: 2021-06-28 18:34:59 +00:00)


In [5]:
df.head()

name  diameter  weight  red  green  blue
0  orange      2.96   86.76  172     85     2
1  orange      3.91   88.05  166     78     3
2  orange      4.42   95.17  156     81     2
3  orange      4.47   95.60  163     81     4
4  orange      4.48   95.76  161     72     9

time: 21 ms (started: 2021-06-28 18:34:59 +00:00)


In [6]:
df.tail()

name  diameter  weight  red  green  blue
9995  grapefruit     15.35  253.89  149     77    20
9996  grapefruit     15.41  254.67  148     68     7
9997  grapefruit     15.59  256.50  168     82    20
9998  grapefruit     15.92  260.14  142     72    11
9999  grapefruit     16.45  261.51  152     74     2

time: 19.9 ms (started: 2021-06-28 18:34:59 +00:00)


In [7]:
df.dtypes

name         object
diameter    float64
weight      float64
red           int64
green         int64
blue          int64
dtype: object

time: 6.01 ms (started: 2021-06-28 18:34:59 +00:00)


In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   name      10000 non-null  object 
 1   diameter  10000 non-null  float64
 2   weight    10000 non-null  float64
 3   red       10000 non-null  int64  
 4   green     10000 non-null  int64  
 5   blue      10000 non-null  int64  
dtypes: float64(2), int64(3), object(1)
memory usage: 468.9+ KB
time: 13.4 ms (started: 2021-06-28 18:34:59 +00:00)


Mengubah string yang ada pada kolom 'name' menjadi bilangan numerik

In [9]:
df['name'][df['name'] == 'orange'] = 0 
df['name'][df['name'] == 'grapefruit'] = 1

time: 13 ms (started: 2021-06-28 18:34:59 +00:00)


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [10]:
df.head()

name  diameter  weight  red  green  blue
0    0      2.96   86.76  172     85     2
1    0      3.91   88.05  166     78     3
2    0      4.42   95.17  156     81     2
3    0      4.47   95.60  163     81     4
4    0      4.48   95.76  161     72     9

time: 13.7 ms (started: 2021-06-28 18:34:59 +00:00)


In [11]:
df.tail()

name  diameter  weight  red  green  blue
9995    1     15.35  253.89  149     77    20
9996    1     15.41  254.67  148     68     7
9997    1     15.59  256.50  168     82    20
9998    1     15.92  260.14  142     72    11
9999    1     16.45  261.51  152     74     2

time: 15.2 ms (started: 2021-06-28 18:34:59 +00:00)


In [12]:
value = df.values
value

array([[0, 2.96, 86.76, 172, 85, 2],
       [0, 3.91, 88.05, 166, 78, 3],
       [0, 4.42, 95.17, 156, 81, 2],
       ...,
       [1, 15.59, 256.5, 168, 82, 20],
       [1, 15.92, 260.14, 142, 72, 11],
       [1, 16.45, 261.51, 152, 74, 2]], dtype=object)

time: 8.9 ms (started: 2021-06-28 18:34:59 +00:00)


Kolom 1 atau kolom 'name' sebagai label dan kolom sisanya sebagai fitur

In [13]:
X = value[:, 1:6]
Y = value[:, 0]

time: 2.35 ms (started: 2021-06-28 18:34:59 +00:00)


In [14]:
X

array([[2.96, 86.76, 172, 85, 2],
       [3.91, 88.05, 166, 78, 3],
       [4.42, 95.17, 156, 81, 2],
       ...,
       [15.59, 256.5, 168, 82, 20],
       [15.92, 260.14, 142, 72, 11],
       [16.45, 261.51, 152, 74, 2]], dtype=object)

time: 6.39 ms (started: 2021-06-28 18:34:59 +00:00)


In [15]:
Y

array([0, 0, 0, ..., 1, 1, 1], dtype=object)

time: 4.48 ms (started: 2021-06-28 18:34:59 +00:00)


NN bekerja dengan baik pada rentang 0-1, oleh karena itu kita perlu mengubah nilai pada fitur menggunakan MinMaxScaler

In [16]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

X_scaler = scaler.fit_transform(X)
X_scaler

array([[0.        , 0.        , 0.74025974, 0.63529412, 0.        ],
       [0.07042254, 0.00738197, 0.66233766, 0.55294118, 0.01851852],
       [0.10822832, 0.04812589, 0.53246753, 0.58823529, 0.        ],
       ...,
       [0.93624907, 0.97133047, 0.68831169, 0.6       , 0.33333333],
       [0.96071164, 0.99216023, 0.35064935, 0.48235294, 0.16666667],
       [1.        , 1.        , 0.48051948, 0.50588235, 0.        ]])

time: 318 ms (started: 2021-06-28 18:34:59 +00:00)


Akan dipisahkan data sebagai data train dan data test

In [17]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X_scaler, Y, test_size = 0.3, random_state = 0)

time: 16.9 ms (started: 2021-06-28 18:35:00 +00:00)


In [18]:
Y_train = Y_train.astype('float32')
Y_test = Y_test.astype('float32')

time: 1.61 ms (started: 2021-06-28 18:35:00 +00:00)


In [19]:
model = tf.keras.models.Sequential([
                                    tf.keras.layers.Dense(units=32, activation='relu', input_shape=(5,)),
                                    tf.keras.layers.Dense(units=32, activation='relu'),
                                    tf.keras.layers.Dense(units=1, activation='sigmoid')
])

time: 53.3 ms (started: 2021-06-28 18:35:00 +00:00)


In [20]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 32)                192       
_________________________________________________________________
dense_1 (Dense)              (None, 32)                1056      
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 33        
Total params: 1,281
Trainable params: 1,281
Non-trainable params: 0
_________________________________________________________________
time: 2.52 ms (started: 2021-06-28 18:35:00 +00:00)


In [21]:
model.compile(
    optimizer='sgd',
    loss = 'binary_crossentropy',
    metrics = ['accuracy']
)

time: 13 ms (started: 2021-06-28 18:35:00 +00:00)


In [22]:
history = model.fit(
    X_train,
    Y_train,
    epochs = 100
)

Epoch 1/100
219/219 [==============================] - 1s 912us/step - loss: 0.6550 - accuracy: 0.7767
Epoch 2/100
219/219 [==============================] - 0s 883us/step - loss: 0.6023 - accuracy: 0.9091
Epoch 3/100
219/219 [==============================] - 0s 1ms/step - loss: 0.5317 - accuracy: 0.9131
Epoch 4/100
219/219 [==============================] - 0s 899us/step - loss: 0.4429 - accuracy: 0.9223
Epoch 5/100
219/219 [==============================] - 0s 907us/step - loss: 0.3544 - accuracy: 0.9234
Epoch 6/100
219/219 [==============================] - 0s 932us/step - loss: 0.2880 - accuracy: 0.9270
Epoch 7/100
219/219 [==============================] - 0s 867us/step - loss: 0.2460 - accuracy: 0.9277
Epoch 8/100
219/219 [==============================] - 0s 892us/step - loss: 0.2211 - accuracy: 0.9271
Epoch 9/100
219/219 [==============================] - 0s 904us/step - loss: 0.2067 - accuracy: 0.9291
Epoch 10/100
219/219 [==============================] - 0s 837us/step - los

In [23]:
model.evaluate(X_test, Y_test)

94/94 [==============================] - 0s 758us/step - loss: 0.1752 - accuracy: 0.9240


[0.17518921196460724, 0.9240000247955322]

time: 222 ms (started: 2021-06-28 18:35:20 +00:00)


In [24]:
def get_label(array):
  prediction = model.predict([array])
  if prediction == 0:
    return print('The fruit is Citrus')
  else:
    return print('The fruit is Grapefruit')

time: 1.5 ms (started: 2021-06-28 18:35:20 +00:00)


In [25]:
sample_1 = [4, 100, 180, 85, 4]
sample_2 = [12, 200, 140, 70, 13]

time: 1.91 ms (started: 2021-06-28 18:35:20 +00:00)


In [26]:
get_label(sample_1)

The fruit is Citrus
time: 92.3 ms (started: 2021-06-28 18:35:20 +00:00)


In [27]:
get_label(sample_2)

The fruit is Grapefruit
time: 45.9 ms (started: 2021-06-28 18:35:20 +00:00)
